version: "3"
services:
    web:
        build: ./docker/builds/php/7.1
        ports:
            - "80:80"
        volumes:
            - "./:/var/www/html"
            - "./docker/confs/000-default.conf:/etc/apache2/sites-available/000-default.conf"
        links:
            - banco
    banco:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=S3G5H7@sfg
            - MYSQL_DATABASE=gfcc
        volumes:
            - "./docker/database:/var/lib/mysql"

